---
title: "Unidad 1. Introducción y Bases."
output:
  html_document:
    toc: true
---

## Introducción.

A lo largo del día escuchamos conceptos como crédito, tasa de interés, capital, monto, interés sobre interés, amortización, deuda, anualidades, etcétera. Eso es especialmente común cuando ya se llega a cierta edad y se contraen responsabilidades al querer adquirir productos o servicios. La mayoría del tiempo comprendemos a qué se refieren, pero siempre existirá algo que se nos escape o no sepamos exactamente a qué se refiere o cómo funciona. Sin embargo, es necesario que sí tengamos al menos la noción de lo que todos estos elementos implican, porque afectan algo que en el estado actual del mundo es sumamente importante: el dinero. El dinero es uno de los mayores inventos de la Humanidad y es, curiosamente, un concepto hasta cierto punto metafórico. El dinero no es la moneda o el billete. Es «cualquier cosa que la gente esté dispuesta a utilizar para representar de manera sistemática el valor de otras cosas con el propósito de intercambiar bienes y servicios.» ( _Yuval Noah Harari. (2014). Sapiens: De animales a dioses. España: Debate._). Por lo tanto, el dinero obtiene su valor del trato entre dos entidades. La manera en la que el dicho valor se comporta, es lo que se abordará.

Como su nombre lo indica, la materia se centra en la aplicación de las Matemáticas a las Finanzas, poniendo énfasis en la manera en la que el dinero cambia su valor con respecto al tiempo y cómo también debe pagarse por el uso de dinero que no nos pertenece (el crédito). Por lo tanto, en el curso nos centraremos en analizar y comprender la relación que existe entre el dinero con el que contamos (le llamaremos Capital), el tiempo -o Plazo-, que transcurre mientras conservamos o prestamos dicho dinero y la Tasa, que viene siendo la proporción de cambio del valor de nuestro dinero. Más adelante abordaremos esos temas, los cuales implican el uso de ciertas herramientas matemáticas. Dichas herramientas se estudiarán en la presente unidad.

## Porcentaje.

Con este término nos referimos a cuando queremos obtener una proporción en relación con cada cien unidades. Por ejemplo, cuando nos referimos a 5 de cada 100 piezas, estamos hablando del 5%. La conversión entre un porcentaje y su equivalente decimal puede obtenerse simplemente dividiendo el propio porcentaje entre cien y quitando el símbolo $\%$. El camino inverso se sigue cuando queremos convertir un decimal a porcentaje, multiplicamos por cien y agregamos el $\%$. Así:

- $1\%$ significa 1 de cada 100 unidades y es equivalente a 0.01.

$$
1\%=\frac{1}{100}=0.01=(0.01)(100)\%=1\%
$$

- $10\%$ significa 10 de cada 100 unidades y es equivalente a 0.10.

$$
10\%=\frac{10}{100}=0.1=(0.1)(100)\%=10\%
$$

- $0.1\%$ significa 0.1 de cada 100 unidades y es equivalente a 0.001.

$$
0.1\%=\frac{0.1}{100}=0.001=(0.001)(100)\%=0.1\%
$$

- $100\%$ significa 100 de cada 100 unidades y es equivalente a 1.

$$
100\%=\frac{100}{100}=1=(1)(100)\%=100\%
$$

### Cómo calcular porcentajes

Abordaremos los dos procedimientos usuales, de porcentaje a cantidad y viceversa.

#### De porcentaje a cantidad

Dado un porcentaje respecto a una cantidad, simplemente se multiplica la cantidad por el porcentaje convertido a decimal.

- El 15% de 600: 

$$
\frac{15\%}{100}\cdot 600=0.15\cdot 600=90
$$

- El 8% de 750:

$$
\frac{8\%}{100}\cdot 750=0.08\cdot 750=60
$$

- El 105% de 20:

$$
\frac{105%}{100}\cdot 20=1.05\cdot 20=21
$$

- En México se cobra el 16% de Impuesto al Valor Agregado (IVA), el cual se cobra sobre el valor del producto. Supongamos que adquiriremos un producto cuyo precio sin el impuesto es de \$255.00. ¿Cuánto pagaremos de IVA? ¿Cuánto pagaremos en total?

$$
\text{IVA}\rightarrow \frac{16}{100}\cdot 255=0.16\cdot255= 40.8\\
\text{Total a pagar}\rightarrow 255+40.8=295.8\ \\ \text{o directamente}\rightarrow255(1+\frac{16}{100})=295.8
$$

- Por cierre de temporada una tienda departamental ofrece un 25% de descuento sobre el precio normal en pantalones. Si deseamos comprar un pantalón cuyo precio normal es de $450, ¿de cuánto es el descuento? ¿cuánto pagaremos?

$$
\text{Descuento}\rightarrow \frac{25}{100}\cdot 450=112.5\\
\text{Total a pagar}\rightarrow 450-112.5=337.5\\
\text{o directamente}\rightarrow 450\left(1-\frac{25}{100}\right)=337.5
$$

#### De cantidad a porcentaje

La otra situación que puede presentarse es que se necesite calcular el porcentaje equivalente a una cantidad, respecto de otra cantidad. En ese caso se multiplica la cantidad deseada por cien y se divide entre la cantidad total. Por ejempo:

- ¿Qué porcentaje de 500 es 60?

$$
\left(\frac{60\cdot 100}{500}\right)\%=12\%
$$

- ¿Qué porcentaje de 18 es 23?

$$
\left(\frac{23\cdot 100}{18}\right)\%\approx 127.778\%
$$

- Un producto tenía un precio de $25.00 hace una semana. Ahora cuesta 28.90. Expresado en porcentaje, ¿de cuánto ha sido el cambio en el precio?

$$
\left(\frac{28.90\cdot 100}{25}\right)\%= 115.6\%\\
\text{El precio ha aumentado un 15.6%.}
$$

- Los niveles de ventas diarias de una compañía han pasado de 3,600 unidades a 3,240. ¿De cuánto ha sido el cambio expresado en porcentaje? Para este tipo de problemas, necesitamos calcular a qué porcentaje equivalen esos 3,240 con respecto a las ventas originales. 

$$
\text{Porcentaje}\rightarrow \left(\frac{3240\cdot100}{3600}\right)\%=90\%\\
\text{Como las ventas han bajado en un 90%, entonces}\\
\text{el cambio es del 10% a la baja}
$$

#### De cantidad y porcentaje a cantidad total

Dada la cantidad resultante, ahora es necesario encontrar el porcentaje respecto de una cantidad. Por ejemplo, ¿de qué cantidad es 60 el 15%?

$$
\frac{60\cdot 100}{15}=400
$$

- 28 es el 35% de una cantidad que no conocemos, ¿cuál es esa cantidad?

$$
\frac{28\cdot 100}{35}=80
$$

- Nos ha llegado una notificación diciendo que hemos recibido un adelanto del 20% del pago por un servicio. La cantidad depositada es de $3,600. ¿A cuánto asciende el precio del servicio?

$$
\frac{3600\cdot 100}{20}=18,000
$$

## Progresiones aritméticas.

Es una sucesión de números, llamados _términos_, en la que cualquier término posterior al primero puede obtenerse del anterior, sumándole (o restándole) un número constante llamado diferencia común ( __d__). Así, por ejemplo: 

$$
5, 8, 11, 14, ...
$$

Es una progresión aritmética cuya diferencia es $3$, ya que el siguiente número se obtiene siempre sumando esta cantidad. Así, el número que sigue es $17$, luego el $20$.

Otro ejemplo es la siguiente progresión:

$$
30,24,18,12,6,0,-6,...
$$

En este caso tenemos una progresión cuya distancia es «negativa», es decir, hay que restarla para obtener el siguiente término. Por lo tanto, $r = -6$.

Podemos ya definir algunas variables que nos ayudarán a desarrollar progresiones aritméticas y calcular términos que en algún momento desconozcamos: $a= $ primer término; $d= $ distancia entre términos; $n= $ número de términos; $u= $ último término. 

### Cálculo del último término

Con esto, podemos enunciar la primera fórmula, la cual nos permitirá encontrar el último término de una progresión aritmética, conociendo el número de términos, el primero y la distancia entre ellos:

$$
u=a+d(n-1)
$$

Obtengamos el último término de una progresión formada por 15 términos, la cual comienza en 4 y la distancia es de 2:

$$
a=4\\
d=2\\
n=15\\
u=¿?\\
\ \\
u=a+d(n-1)=4+2(15-1)=4+2(14)=4+28=32\\
u=32
$$

__Aplicado__. Debe realizar unos pagos de manera mensual, siendo 12 el número total de estos. Sabe que el primero es de $\$250$, el segundo de $\$240$ y el tercero de $\$230$. ¿De cuánto será el último pago?

__R:__. Primero, obtenemos la distancia entre términos y enseguida organizamos los datos. La distancia es fácil obtenerla, ya que sabemos que es la diferencia entre términos. El primero es 250 y el segundo es 240, es decir, $240-250=-10$; por lo cual hay una diferencia negativa de $\10$. Ahora organicemos:

$$
n=12\ pagos\\
a=250\\
d=-10\\
u=?
$$

Ahora calculamos el último término con la fórmula que toca:

$$
u=a+d(n-1)=250+(-10)(12-1)=250+(-10)(11)=250-110=140
$$

El último pago será de $\$140$.

### Cálculo del primer término

Ahora bien, conociendo el último de los términos, la distancia y el número de ellos, ¿es posible encontrar el primero? Despejemos la fórmula anterior:

$$
u=a+d(n-1)\rightarrow a=u-d(n-1)
$$

¿Cuál es el primer término de una progresión si el último es 32, siendo 2 la distancia entre los 15 que la conforman?

$$
a=¿?\\
d=2\\
n=15\\
u=32\\
\ \\
a=u-d(n-1)=32-2(15-1)=32-2(14)=32-28=4\\
a=4
$$

### Cálculo de la distancia

Retomando el mismo ejemplo, ¿es posible encontrar la distancia entre los términos de una progresión que comienza en 4, termina en 32 y contiene 15 valores? Desarrollemos la fórmula y probemos:

$$
u=a+d(n-1)\rightarrow u-a=d(n-1)\rightarrow \frac{u-a}{n-1}=d\\
d=\frac{u-a}{n-1}
$$

Muy bien, ya tenemos la fórmula. Calculemos entonces la distancia:

$$
a=4\\
d=¿?\\
n=15\\
u=32\\
\ \\
d=\frac{u-a}{n-1}=\frac{32-4}{15-1}=\frac{28}{14}=2\\
d=2
$$

### Cálculo del número de términos

También es posible encontrar el número de términos que entran en una progresión aritmética si ya conocemos el primero, el último y la distancia que existe entre ellos. Retomando el ejemplo, despejemos la fórmula y probemos que es 15:

$$
u=a+d(n-1)\rightarrow u-a=d(n-1)\rightarrow\frac{u-a}{d}=n-1\\
\rightarrow\frac{u-a}{d}+1=n\rightarrow n=\frac{u-a}{d}+1
$$

$$
a=4\\
d=2\\
n=¿?\\
u=32\\
\ \\
n=\frac{u-a}{d}+1 = \frac{32-4}{2}+1=\frac{28}{2}+1=14+1=15\\
n=15
$$

### Suma de una progresión aritmética

Así como podemos calcular cualquier término, también es posible encontrar la suma de todos los términos en una progresión. La fórmula que nos permite dicho cálculo es :

$$
S=\frac{n(a+u)}{2}
$$

Veamos unos ejemplos:

#### Ejemplos

Encontremos la suma de los primeros treinta términos de la progresión aritmética $15;21;27;...$

Lo primero que debemos hacer es encontrar el último número a partir de los datos. Sabemos que el primero es 15 y el segundo es 21, por lo tanto la distancia existente es de $21-15=6$. Podemos saber la distancia restando el primer elemento del segundo. Ahora encontremos el último término aplicando la fórmula que corresponde:

$$
n=30\\
a=15\\
d=6\\
u=?\\
\ \\
u=a+d(n-1)=15+6(30-1)=15+6(29)=15+174=189\\
\ \\
u=189
$$

Ahora que ya tenemos al último término, apliquemos la fórmula de la suma:

$$
S=\frac{n(a+u)}{2}=\frac{30(15+189)}{2}=\frac{30(204)}{2}=\frac{6120}{2}=3060
$$

__Aplicado__. Supongamos que tenemos que realizar 10 pagos con uno inicial por $\$650$. Sabemos que también irá disminuyendo el valor del pago por una diferencia de $\$25$. ¿Cuál será el valor total de la deuda?

Primero debemos encontrar el valor del último pago. Para ello utilizamos la fórmula del último término. Cuando ya lo tengamos podemos calcular la sumatoria.

$$
a=650\\
d=-25\\
n=10\\
u=?\\
\ \\
u=a+d(n-1) \rightarrow 650+(-25)(10-1)=650+(-225)=425\\
\ \\
u=425
$$

Calculemos el valor de la suma de la progresión:

$$
S=\frac{n(a+u)}{2}=\frac{10(650+425)}{2}=\frac{10(1075)}{2}=\frac{10750}{2}=5375
$$

El valor total de los pagos es de $\$5,375$.

## Progresiones geométricas.

Una progresión geométrica es una sucesión de términos, en la que cualquier término posterior al primero puede obtenerse del anterior, multiplicando (o dividiendo) un número constante llamado razón ( __r__). Así, por ejemplo: 

$$
4,12,36,108,...
$$

En esta secuencia podemos ver que el primer número es 4 y el siguiente es 12. Podríamos creer que es una progresión aritmética con distancia de 8. Eso haría que el tercer término fuera 20. Pero no es así. Esto se debe a que la progresión no es aritmética, sino geométrica. Así como la distancia entre términos de la progresión aritmética se obtiene restándole el primer término al segundo, en la geométrica se obtiene dividiendo el segundo término entre el primero:

$$
r=\frac{12}{4}=3\\
\ \\
r=3
$$

Solo que no se le conoce como distancia, si no como _razón_. Sabiendo esto, tomemos el segundo término y multipliquémoslo por la razón. Esto debe dar como resultado el tercer término:

$$
(12)(3)=36;\\
(36)(3)=108;\\
(108)(3)=324;\\
...
$$

Sabiendo esto, enunciamos las fórmulas que nos permitirán calcular el último, el primero o el total de términos, la razón sin tener la progresión y la suma de todos ellos.

## Último término

$$
u=ar^{n-1}
$$

Por ejemplo, encontremos cuál es el último término de una progresión de 6 números cuyo primero es 5 y la razón es de 8.

$$
a=5\\
n=6\\
r=8\\
u=?\\
\ \\
u=ar^{n-1}=5(8)^{6-1}=5(8)^5=5(32768)=163840\\
\ \\
u=163,840
$$

## Logaritmos.




